repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/.*\.py$

  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        files: ^backend/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - --config-file
          - mypy.ini
          - backend/app
          - backend/tests
        additional_dependencies:
          - python-dotenv
          - types-requests
          - types-setuptools
          - types-PyYAML
          - types-networkx
          - pandas-stubs
          - types-tqdm
          - sqlalchemy2-stubs
          - types-psycopg2
          - pydantic
          - fastapi